sequenceDiagram
    participant browser
    participant server

    Note right of browser: User creates a new note and clicking the "Save" button.
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note (data: { content: "User's note content", date: "current date" })
    activate server
    server-->>browser: 302 Found (redirect to /notes)
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: Html document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: Css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The JavaScript fetches the updated JSON data

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: Updated JSON data [{ "content": "hello", "date": "2025-09-11" }, ... ]
    deactivate server

    Note right of browser: Browser renders the updated list of notes